const users = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    name: "Admin",
    role: "admin",
    email: "testprep952@gmail.com",
    password: "Nalani@20241",
    imageurl: "/image-avatar.png",
  },
];

const tutoringStudents = [
  {
    name: "Emma Johnson",
    email: "emma.johnson@example.com",
    phone: "+1-202-555-0134",
    level: "High School",
    startDate: new Date("2025-05-10"),
    subjectHelp: "Algebra I & II",
    assistant: "Samuel Bako",
    status: "Pending",
    supportType: "Tutoring",
  },
  {
    name: "Oliver Smith",
    email: "oliver.smith@example.co.uk",
    phone: "+44 7911 123456",
    level: "A-Level",
    startDate: new Date("2025-05-12"),
    subjectHelp: "General Physics",
    assistant: "Mary Obi",
    status: "In Progress",
    supportType: "Tutoring",
  },
  {
    name: "Ava Brown",
    email: "ava.brown@example.ca",
    phone: "+1-416-555-0198",
    level: "College",
    startDate: new Date("2025-05-15"),
    subjectHelp: "Organic Chemistry",
    assistant: "Daniel Eze",
    status: "Pending",
    supportType: "Tutoring",
  },
  {
    name: "Liam Patel",
    email: "liam.patel@example.nz",
    phone: "+64 21 123 4567",
    level: "High School",
    startDate: new Date("2025-05-18"),
    subjectHelp: "Biology (Human Anatomy)",
    assistant: "Joy Udoh",
    status: "Completed",
    supportType: "Tutoring",
  },
  {
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    phone: "+1-310-555-0177",
    level: "A-Level",
    startDate: new Date("2025-05-20"),
    subjectHelp: "English Literature",
    assistant: "Charles Nneji",
    status: "In Progress",
    supportType: "Tutoring",
  },
  {
    name: "Noah Davies",
    email: "noah.davies@example.co.uk",
    phone: "+44 7700 900123",
    level: "College",
    startDate: new Date("2025-05-22"),
    subjectHelp: "European History",
    assistant: "Ruth Abubakar",
    status: "Pending",
    supportType: "Tutoring",
  },
  {
    name: "Isla Macdonald",
    email: "isla.macdonald@example.ca",
    phone: "+1-438-555-0142",
    level: "High School",
    startDate: new Date("2025-05-25"),
    subjectHelp: "World Literature",
    assistant: "Sola Adedeji",
    status: "Pending",
    supportType: "Tutoring",
  },
];

const examPrepStudents = [
  {
    name: "Ethan Clark",
    email: "ethan.clark@example.com",
    phone: "+1-646-555-0101",
    level: "A-Level",
    startDate: new Date("2025-05-11"),
    exam: "SAT",
    examDate: new Date("2025-07-01"),
    subjectHelp: "SAT Math",
    assistant: "Vivian Chika",
    status: "In Progress",
    supportType: "Exam Prep",
  },
  {
    name: "Mia Taylor",
    email: "mia.taylor@example.co.uk",
    phone: "+44 7400 123789",
    level: "High School",
    startDate: new Date("2025-05-13"),
    exam: "IELTS",
    examDate: new Date("2025-06-15"),
    subjectHelp: "IELTS English Writing",
    assistant: "David Umeh",
    status: "Pending",
    supportType: "Exam Prep",
  },
  {
    name: "Lucas Tremblay",
    email: "lucas.tremblay@example.ca",
    phone: "+1-514-555-0133",
    level: "College",
    startDate: new Date("2025-05-14"),
    exam: "WAEC",
    examDate: new Date("2025-08-01"),
    subjectHelp: "WAEC Chemistry",
    assistant: "Ifeoma Okonkwo",
    status: "In Progress",
    supportType: "Exam Prep",
  },
  {
    name: "Chloe Singh",
    email: "chloe.singh@example.nz",
    phone: "+64 22 456 7890",
    level: "A-Level",
    startDate: new Date("2025-05-16"),
    exam: "TOEFL",
    examDate: new Date("2025-06-30"),
    subjectHelp: "TOEFL Reading & Writing",
    assistant: "Peter Etim",
    status: "Pending",
    supportType: "Exam Prep",
  },
  {
    name: "Benjamin Miller",
    email: "ben.miller@example.com",
    phone: "+1-718-555-0115",
    level: "High School",
    startDate: new Date("2025-05-17"),
    exam: "SAT",
    examDate: new Date("2025-07-05"),
    subjectHelp: "SAT Physics",
    assistant: "Amina Yusuf",
    status: "Completed",
    supportType: "Exam Prep",
  },
  {
    name: "Emily White",
    email: "emily.white@example.co.uk",
    phone: "+44 7500 112233",
    level: "College",
    startDate: new Date("2025-05-19"),
    exam: "WAEC",
    examDate: new Date("2025-08-10"),
    subjectHelp: "WAEC Biology",
    assistant: "Obinna Eze",
    status: "Pending",
    supportType: "Exam Prep",
  },
  {
    name: "Jack O'Reilly",
    email: "jack.oreilly@example.nz",
    phone: "+64 27 987 6543",
    level: "A-Level",
    startDate: new Date("2025-05-21"),
    exam: "IELTS",
    examDate: new Date("2025-06-18"),
    subjectHelp: "IELTS Reading",
    assistant: "Sarah Abiodun",
    status: "Pending",
    supportType: "Exam Prep",
  },
];

const endToEndSupportStudents = [
  {
    name: "Henry Anderson",
    email: "henry.a@example.com",
    phone: "+1-408-555-0189",
    level: "High School",
    startDate: new Date("2025-05-09"),
    exam: "NECO",
    examDate: new Date("2025-08-20"),
    subjectHelp: "NECO English (Essay + Comprehension)",
    assistant: "Nneka Bello",
    status: "In Progress",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Grace Evans",
    email: "grace.evans@example.co.uk",
    phone: "+44 7555 445566",
    level: "College",
    startDate: new Date("2025-05-10"),
    exam: "GCE",
    examDate: new Date("2025-09-05"),
    subjectHelp: "GCE History - Modern Europe",
    assistant: "Kenneth Ajayi",
    status: "Pending",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Jacob Dubois",
    email: "jacob.dubois@example.ca",
    phone: "+1-581-555-0176",
    level: "A-Level",
    startDate: new Date("2025-05-13"),
    exam: "WAEC",
    examDate: new Date("2025-07-15"),
    subjectHelp: "WAEC Chemistry - Inorganic",
    assistant: "Halima Sani",
    status: "Pending",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Aria Thompson",
    email: "aria.thompson@example.nz",
    phone: "+64 29 345 6789",
    level: "College",
    startDate: new Date("2025-05-14"),
    exam: "SAT",
    examDate: new Date("2025-07-25"),
    subjectHelp: "AP Math & SAT Math Level 2",
    assistant: "Grace Mordi",
    status: "In Progress",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Nathan Scott",
    email: "nathan.scott@example.com",
    phone: "+1-303-555-0123",
    level: "High School",
    startDate: new Date("2025-05-15"),
    exam: "IELTS",
    examDate: new Date("2025-06-28"),
    subjectHelp: "IELTS Speaking & Listening",
    assistant: "Emmanuel Nnaji",
    status: "Completed",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Charlotte Hughes",
    email: "charlotte.h@example.co.uk",
    phone: "+44 7700 889977",
    level: "A-Level",
    startDate: new Date("2025-05-18"),
    exam: "NECO",
    examDate: new Date("2025-08-30"),
    subjectHelp: "NECO Biology - Cell Structure",
    assistant: "Sade Ogunleye",
    status: "Pending",
    supportType: "End-to-End Exam Support",
  },
  {
    name: "Logan Campbell",
    email: "logan.campbell@example.nz",
    phone: "+64 21 234 5678",
    level: "College",
    startDate: new Date("2025-05-20"),
    exam: "TOEFL",
    examDate: new Date("2025-07-20"),
    subjectHelp: "TOEFL Listening & Writing",
    assistant: "Tunde Bakare",
    status: "Pending",
    supportType: "End-to-End Exam Support",
  },
];

export { users, tutoringStudents, examPrepStudents, endToEndSupportStudents };
